silverstripe/silverstripe-admin

client/dist/styles/bundle.css
client/src/components/Breadcrumb/Breadcrumb.scss
client/src/styles/_variables.scss

This is a quick fix to ensure breadcrumbs and north toolbar headings look consistent (even though markup/styles are still inconsistent). 
Fixes: https://github.com/silverstripe/silverstripe-admin/issues/22
Fixes: https://github.com/silverstripe/silverstripe-framework/issues/6757
Related issue to improve the consistency of overall markup and styles for breadcrumbs/toolbar https://github.com/silverstripe/silverstripe-admin/issues/23

Make breadcrumbs and toolbar title position consistent

---

client/dist/styles/bundle.css
client/src/styles/legacy/TreeDropdownField.scss

https://github.com/silverstripe/silverstripe-framework/issues/5702
I'd say just remove the status indicators. Pointer for how to fix: Make a change to a page and only save it without publication, which should cause a "modified" status in the tree. Go to admin/pages/add and choose "under another page". The _tree.scss styles contain a tree-status-icon mixin which is responsible for this styling. That's not replicated in TreeDropdownField.scss

Remove status indicators on the Tree dropdown items text.

---

client/dist/js/bundle.js
client/src/lib/DataFormat.js

Fixes a bug where filesizes were being incorrectly calculated as the maths order of operations was not taken into consideration, this also remove decimals for KB
**Related PR:** https://github.com/silverstripe/silverstripe-assets/pull/10
**Related Issue:** https://github.com/silverstripe/silverstripe-asset-admin/issues/355

MINOR: Fix order of operations for filesize calculations

---

client/dist/js/bundle.js
client/src/lib/DataFormat.js
client/src/lib/tests/DataFormat-test.js

This fixes [framework #6663](https://github.com/silverstripe/silverstripe-framework/issues/6663), where the filesize displayed on uploaded images was wrong in most cases. It also adds test coverage to ensure there are no future regressions.

Fix file size calculation in UploadField UI, add test coverage.

---

client/dist/styles/bundle.css
client/src/components/FormBuilderModal/FormBuilderModal.scss
client/src/components/Modal/Modal.scss

Fix close button no longer hidden when success message flowed over modal header
Please see https://github.com/silverstripe/silverstripe-campaign-admin/issues/13 for more details

Unhide close button in modal

---

code/LeftAndMain.php

When creating a new ModelAdmin subclass in 4.0 there is not a matching permission checkbox in the CMS. This is because the root LeftAndMain::providePermissions() handles the creating of the codes and $this->getRequiredPermissions is only called on the root LeftAndMain rather than the target class.

Fix missing permissions codes for ModelAdmins

---

themes/cms-forms/templates/SilverStripe/Forms/DatetimeField_holder.ss

The ID gets applied to the <input> having it on the <div> results in a duplicate ID on the page

BUGFIX: Remove duplicate ID

---

webpack-dev.config.js

They're not being used and they're breaking things, e.g. `ExtractTextPlugin`

BUGFIX: Get rid of special dev webpack plugins

---

client/dist/js/bundle.js
client/src/components/TreeDropdownField/TreeDropdownField.js
client/src/components/TreeDropdownField/tests/TreeDropdownField-test.js
client/src/containers/FormBuilderLoader/FormBuilderLoader.js

Fixes https://github.com/silverstripe/silverstripe-asset-admin/issues/217
Adds the feature to select root as an option in the `TreeDropdownField`
Also invalidates cache after changing location (through form schema)
Related pull requests
https://github.com/silverstripe/silverstripe-asset-admin/pull/476
https://github.com/silverstripe/silverstripe-framework/pull/6915

Feature to adding root as an available option and cache invalidation

---

code/CMSMenu.php
tests/php/LeftAndMainTest.php

Issue: https://github.com/silverstripe/silverstripe-framework/issues/6851
* https://github.com/silverstripe/silverstripe-framework/pull/6934

API Consistent use of inst() naming across framework

---

client/dist/styles/bundle.css
client/src/components/Form/Form.scss

Fixes https://github.com/silverstripe/silverstripe-cms/issues/1773#issuecomment-302377616
At extreamly large sizes I've added an max-width which should align all fields on the right.

Extended width of TinyMCE area, with max width align with other fields

---

code/LeftAndMain.php

Fixes https://github.com/silverstripe/silverstripe-cms/issues/1865
**Depends on** https://github.com/silverstripe/silverstripe-framework/pull/7099

Set user themes on TinyMCEConfig before overwriting with admin themes

---

client/src/components/Form/Form.scss
client/src/components/Menu/Menu.scss
client/src/components/PopoverField/PopoverField.scss
client/src/components/Tooltip/Tooltip.scss
client/src/styles/_fonts.scss
client/src/styles/_layout.scss
client/src/styles/editor.scss

I've added `disable-line` comments to lines of css which cannot be avoided or fixed them (such as the multi-line comments)
There were a couple of warnings which I've left as they have an explicit `TODO` around them and makes sense to keep as warnings

Fix linting warnings in sass

---

_config.php

This means that a user can set config in `mysite` or a module that comes alphabetically before `silverstripe-admin` and have it apply, without having to resort to the `zzzmysite` workaround.

check for already set config in tinymce

---

code/LeftAndMain.php

_Initial approach removed_
Users can now disable the CMS help link in user code:
```php
use SilverStripe\Admin\LeftAndMain;
Config::modify()->set(LeftAndMain::class, 'help_link', false);
```

NEW Allow help link to be disabled in user code

---

code/GroupImportForm.php
code/MemberImportForm.php
lang/en.yml
templates/SilverStripe/Admin/Includes/ModelAdmin_ImportSpec.ss

Issue: https://github.com/silverstripe/silverstripe-framework/issues/6582

FIX Remove legacy translation behaviour in template

---

code/CMSMenu.php

This change allows a controller that extends LeftAndMain to set a `private static $ignore_menuitem = true` so `CMSMenu::get_menu_items` will ignore it.
Some context about the reason for this change
* In SS3 a sub class of LeftAndMain is allowed without a `$url_segment`
* In SS4 the `$url_segment` is required
* The presence of a `$url_segment` is what is currently used to determine whether to add the result of `CMSMenu::menuitem_for_controller` to the menu items stack (see `::get_menu_items`). This means that a LeftAndMain subclass from SS3 would previously not have been in this stack, whereas in SS4 is now is (example is `SubsiteXHRController` in the subsites module)
* If that subclass of LeftAndMain has a `canView` method which calls `CMSMenu::get_viewable_menu_items` (like that subsites …

FIX Allow CMSMenuItem creation to be skipped for LeftAndMain implementations

---

.htaccess
_config.php
code/ModelAdmin.php
composer.json

See https://github.com/silverstripe/silverstripe-framework/issues/7405
Merge after https://github.com/silverstripe/silverstripe-framework/pull/7395
Manually tested by opening and saving `admin/pages` (incl. regenerating tinymce_gzip files in live mode). 
Test (after merging the framework pull request):
```
composer config repositories.admin vcs https://github.com/open-sausages/silverstripe-admin.git
composer require "silverstripe/siteconfig:dev-pulls/1/vendorise-me-baby as 1.0.x-dev"
```

Expose as vendor module

---

templates/SilverStripe/Admin/Includes/LeftAndMain_MenuStatus.ss

Resolves #139
Ironically when testing, the default admin's first name is Default Admin so you initially see no difference.
We could possibly look at removing the right padding on `.cms-login-status__profile-link` to give an extra letter, but this will continue to be a problem for longer first names.

FIX Only show user's first name in CMS header

---

templates/SilverStripe/Admin/Includes/CMSBreadcrumbs.ss

Required to add support for custom breadcrumb designs such as https://projects.invisionapp.com/share/2MDS99OTZ#/screens/256544889. This allows the breadcrumb to specify either HTML or Varchar support.
See related PRs:

Allow breadcrumbs to define HTML support or not.

---

tests/php/LeftAndMainTest.php

The assertions in the foreach loop don't run, because `$menuItems` returns an empty ArrayList. This means the test is "risky".

FIX Ensure testLeftAndMainSubclasses test runs some assertions

---

templates/SilverStripe/Admin/Includes/LeftAndMain_MenuLogo.ss

The span tag that displays the application name and version contains a typo

HTML typo in cms template

---

package.json
yarn.lock

When running on a shared drive through a VM, I have to use `--no-bin-links` when running `yarn`; these changes help with that.
Also, webpack isn't a direct dependency of the package, even though we need it, so this declares it correctly.

Make webpack work nicely when bin-links are off

---

.gitattributes

The font directory includes `icons-reference.html`, which is _really_ useful for picking icons.

Don't include font source in export-ignore

---

client/src/components/FormAlert/README.md
client/src/components/FormAlert/tests/FormAlert-story.js

Fixes #506 (story book issue)
This PR clarifies that providing the closeLabel prop will make the alert dismissible.

MINOR Clarify that closeLabel will make alerts dismissible, fix story book example

---

client/src/components/FormAction/README.md
client/src/components/FormAction/tests/FormAction-story.js

We had a case in campaign-admin where the wrong outline classes were used, so I've added some quick examples to the pattern library.

NEW Pattern library now has FormAction examples

---

client/src/lib/dependency-injection/tests/loadComponent-test.js

Fixing #524 .
I've added a MockStore to the loadComponent ApolloProvider provider test to suppress the warning that Apollo requires a redux store.

Fix Add mock store to the loadComponent ApolloProvider

---

code/LeftAndMain.php

Original author: @dhensby
Forward port from 3.7 fix at https://github.com/silverstripe/silverstripe-framework/pull/8318

Make sure that CMS requests disable caching

---

code/LeftAndMain.php

Implements #632. I went with an approach that avoids API changes, whilst being as flexible as possible.

Make section name in Client Config configurable.

---

_config/injector.yml
_config/routes.yml

```
PHP Deprecated: Not quoting the scalar "%$SilverStripe\GraphQL\Manager.admin" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0 on line 9. in /Users/robbieaverill/dev/ss43/vendor/symfony/yaml/Inline.php on line 357
PHP Deprecated: Not quoting the scalar "%$SilverStripe\GraphQL\Controller.admin" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0 on line 4. in /Users/robbieaverill/dev/ss43/vendor/symfony/yaml/Inline.php on line 357
PHP Deprecated: Not quoting the scalar "%$SilverStripe\GraphQL\Manager.default" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0 on line 14. in …
```

FIX Quote injector alias references, deprecated and removed support for in Symfony 4

---

tests/php/LeftAndMainTest.php

FIX Remove deprecated help_link definition in testGetHelpLinks

---

_config/forms.yml
code/Forms/FormMessageBootstrapAdapter.php
templates/SilverStripe/Admin/Includes/CMSProfileController_EditForm.ss
templates/SilverStripe/Admin/Includes/LeftAndMain_EditForm.ss
themes/cms-forms/templates/RightLabelledFieldHolder.ss
themes/cms-forms/templates/SilverStripe/Forms/CheckboxField_holder.ss
themes/cms-forms/templates/SilverStripe/Forms/CompositeField_holder.ss
themes/cms-forms/templates/SilverStripe/Forms/DatetimeField_holder.ss
themes/cms-forms/templates/SilverStripe/Forms/FieldGroup_holder.ss
themes/cms-forms/templates/SilverStripe/Forms/FormField_holder.ss
themes/cms-forms/templates/SilverStripe/Forms/Includes/Form.ss
themes/cms-forms/templates/SilverStripe/Forms/OptionsetField_holder.ss

This adds an extension which provides SilverStripe message types to templates as Bootstrap alert types, and implements them in all of the admin templates that use $MessageType
Issue: https://github.com/silverstripe/silverstripe-framework/issues/5674
Requires https://github.com/silverstripe/silverstripe-framework/pull/8377 to merged for Behat to pass

NEW Use Bootstrap alerts throughout the CMS

---

package.json
yarn.lock

Our beloved pattern library is having some build issues. Looks like the source of the problem is the notes-addon.
I've downgraded it from version 4.0 to 3.4 to put it in line with the other addons which seems to have resolved the problem.

FIX Downgrade to @storybook/addon-notes to 3.4 to allow pattern lib to build

---

client/lang/src/en.json

The translation key for the archive confirmation message is missing from admin.
* #753

FIX Readding ARCHIVECONFIRMMESSAGE

---

client/src/font/tests/Icons-story.js

The pattern lib wasn't working on IE 11 because the Icon story tries to call `forEach` on a nodelist which is not available in IE11.
* https://github.com/silverstripe/silverstripe-admin/issues/794

MINOR FIX Patternlib to work on IE11

---

.travis.yml
tests/behat/features/reauthenticate.feature

Fix wording and remove explicit await for the server response;
From now onward we rely on the testsession:2.2 feature
allowing us to wait transparently for server to respond
after each step.
Requires:

Fix behat reauthenticate tests

---

client/dist/styles/editor.css
client/src/styles/editor.scss

Fixes #850 and fixes https://github.com/silverstripe/silverstripe-externallinks/issues/49

FIX TinyMCE editor.scss now applies to the correct body class, and has correct broken link colours

---

tests/behat/features/manage-users.feature

Broken test: https://travis-ci.org/silverstripe/silverstripe-admin/jobs/527589331
This patch follows up the semantic change made in this patch (buttons became links) - https://github.com/silverstripe/silverstripe-framework/commit/5337e6d04847c66d0a293e9c6c53a58d97aea3a1

Behat test complies with accessible buttons

---

code/LeftAndMain.php

Simple wording update to save time when reviewing this exception - show the class that's probably missing the configuration.

FIX Add offending class to exception message

---

_config.php

SilverStripe 3 had the ability to insert anchors into content areas
within the CMS. SilverStripe 4 however has separated the ideas of the
admin area and the CMS - however the ability for an editor to insert
an anchor is not directly related to pages. To this end the anchor
plugin for TinyMCE should be enabled here, as opposed to globally
for all rich text editors, e.g. enabling for unauthenticated users
adding blog comments shouldn't be done.
This has the knock on affect for the CMS module, where the "link to
an anchor on another page" plugin is also enabled. Since the release
of SilverStripe 4 it has been an option to create such links, but an
editor could not also create the anchors to link to. Now they will be
able to do such.
Partial address of …

FIX re-enable ability to insert anchors

---

.gitignore
.storybook/config.js
.storybook/lib/storyTeller.js
.storybook/scripts/runStoryTeller.js
.storybook/webpack.config.js
.travis.yml
package.json
yarn.lock

Modules that stories need to be gathered from should have a .ss-storybook.js configuration file in their root directory
I'll add some documentation in a framework PR, and then I'll add the `.ss-storybook.js` to asset-admin too.
I can rebase this against the minor branch if required but as this is dev changes I thought it'd be nice to have this storybook enhancement in place for fixing bugs or developing features in modules based on admin@1.4
Fixes #785 
- silverstripe/silverstripe-asset-admin#963

FIX/NEW: Stories are now fetched dynamically from related modules

---

tests/behat/features/manage-users.feature
tests/behat/features/security-permissions.feature

When versioned is installed, it changes the "save" button label which confuses behat.
This PR tests both possible labels when saving members.
* https://github.com/silverstripe/silverstripe-behat-extension/pull/189

BUG Search for both Save and Apply change when runnign behat test

---

code/LeftAndMain.php

Not sure exactly what this piece of code is trying to do, but it's doing it very poorly.
`SecurityAdmin` is the only controller I could find actually relying on it. All the other `LeftAndMain` child class overrides that method any way.
Removing it doesn't seem to lead to obviously bad results. It's not clear to me that there's obvious value in displaying a hierarchy in the breadcrumb even for groups.
* #742

BUG Remove buggy code from LeftAndMain Breadcrumb

---

composer.json

Packagist doesn't like it when dependencies are not all written in lowercase. This is preventing it to resolve 1.2.x-dev as an alias for 1.2.x-dev.

BUG Lowercase PHPUnit in composer.json to allow packagist to resolve 1.2.x-dev

---

code/ModelAdmin.php
tests/php/ModelAdminTest.php
tests/php/ModelAdminTest/ModelAdminExtension.php
tests/php/ModelAdminTest/OverridenModelAdmin.php

This is a sort of RFC/PR.
Many times over the years, I wanted to do a minor tweak to a ModelAdmin gridfield. However, to actually get to the instance of your GridiField, you got to override getEditForm and then fetch your gridfield instance, which will have a different name base on what model the user is currently viewing.
Basically it's unruly and not a very nice developer experience.
My thinking is let's split the ModelAdmin `getEditForm` method into smaller protected methods which will allow developers to override the specific bits they want to customise:
* `getGridField` for the actual field ;
* `getGridFieldConfig` for the config part.
As an added benefit, I also think this makes the code more readable.
We might also want to add a few extra extension points for Extensions to hook …

API Break up ModelAdmin::getEditForm into getGridField and getGridFieldConfig

---

themes/cms-forms/templates/SilverStripe/Forms/SelectionGroup.ss

The SelectionGroup template uses `$Fieldholder` which does get the result of the `FieldHolder` method but doesn't get automatically cast to `HTMLFragment` because casting is case-sensitive. This fixes that.

BUG case error in SelectionGroup template

---

templates/SilverStripe/Admin/Includes/CMSProfileController_Content.ss

FIX "My profile" title in CMS is now vertical centered as other LeftAndMain screens are

---

_config/routes.yml

I’ve had issues getting the URL admin/graphql to work on a ModelAdmin
app that doesn’t have CMS installed. This fix ensures that the graphql
URL rule is inserted before the admin one, making it work.

FIX: Ensure graphql URL is inserted before admin

---

code/LeftAndMain.php
code/ModelAdmin.php

As part of the above PR, there is now a standardised method (`getValidatorList()`) for adding/manipulating `Validators` for a `DataObject`.
This new method provides BC for the old `getCMSValidator()` method.
Tests are expectedly failing, as I have replaced call to `getCMSValidator()` with `getValidatorList()`, which won't exist until the above dependent PR has been merged.
I have, however, run the tests locally (with the dependent PR checked out), and all tests are currently passing.

DEPENDENCY: Replace getCMSValidator with new framework method getCompositeValidator

---

code/ModelAdmin.php
templates/SilverStripe/Admin/Includes/ModelAdmin_Content.ss

The default slug of a sanitised classname will still be in place, but
now the key can be set to a slug and the class provided in a dataClass
property.
This has a couple of benefits:
- Slugs can be shorter (ModelAdmin URLs are verbose, to say the least)
- The same class can be added to a ModelAdmin multiple times, for
example with different filters.
If the dataClass is the same as the slug, backwards compatibility is
preserved. If the slug differs, then code that expected to find the
Slug in $this->modelClass will instead have to check $this->modelTab.
However, as this doesn’t break any upgrades (since the slug will never
differ on those) my view is that it’s minor-upgrade safe.

FIX: Decouple ModelAdmin URL slug from class.

---

code/ModelAdmin.php

The slug flexibility provided in #1072 introduced a bug, which this fixes:
The logic added to getManagedModels() won’t apply if the method is overridden and custom values returned
Note that the bug introduced in 1072 breaks ArchiveAdmin in versioned-admin.

FIX: Fix ModelAdmin slug flex when getManagedModels() is overridden.

---

.travis.yml

ChromeDriver 85.0.4183.83 fixed a security issue however it introduce a bug that causes chromedriver to crash when interacting when some user dialogue. This is preventing us from a running an admin test.
ChromeDriver 85.0.4183.87 fixes the issue, but it hasn't hit the Ubuntu packages repo yet. This is a temporary fix to bypass  this issue.
* blocks https://github.com/silverstripe/silverstripe-admin/pull/1068

BUG Temporary fix to use the most up-tot-date version of chromedriver

---

.gitignore
.travis.yml
composer.json

MNT: Add a prefer-lowest build
In addition, remove the unnecessary duplication in builds, and shift
codesniffer installation to be part of the require-dev deps in keeping
with other repos.

NEW: Confirm PHP 8 support

---

code/ModelAdmin.php
tests/php/ModelAdminTest.php
tests/php/ModelAdminTest/MultiModelAdmin.php

https://github.com/silverstripe/silverstripe-admin/pull/1072 updated the output format of `getManagedModels`. If your `ModelAdmin` has overridden `getManagedModels`, it might still be returning the old format which will cause `getManagedModelTabs` to fall flat on its face. e.g.: [RegistryAdmin](https://github.com/silverstripe/silverstripe-registry/blob/2/src/RegistryAdmin.php#L30)
I'm calling this a semver breakage.
- https://github.com/silverstripe/silverstripe-framework/pull/9837

BUG Update getManagedModelTabs so it can still work with the old output format of getManagedModels

---

.travis.yml

Issue https://github.com/silverstripe/silverstripe-admin/issues/1213
Admin is a bit of strange one that runs both 'admin' and 'cms' behat suites.  It's debatable whether things should be this way, though for now I think we should keep it as is.
This PR will ensure that both behat suites have both graphql 3 and graphql 4 jobs run
The new graphql 3 behat tests are passing, though the graphql 4 build has an existing failure

MNT Ensure graphql 3 versions of behat tests run

---

.travis.yml

Issue https://github.com/silverstripe/silverstripe-admin/issues/1215

MNT Remove pattern-lib, bump frameworktest, resolve merge-conflict

---

.travis.yml

https://github.com/silverstripe/silverstripe-admin/pull/1224/ accidentally removed the NPM test
- https://github.com/silverstripe/silverstripe-admin/issues/1215

MNT Restore NPM test

---

tests/php/ModelAdminTest.php

This [line on SudoModeController](https://github.com/silverstripe/silverstripe-security-extensions/blob/16448058c285b3eb5b6712902f8f7d9fe7becd31/src/Control/SudoModeController.php#L60) expects the request to be registered in Injector.
This breaks the test when the security extension module is installed.
Fixes https://github.com/silverstripe/silverstripe-admin/issues/1219

MNT Fix ModelAdminTest to work with sudo mode

---

code/CMSMenu.php

There's no point CMSMenuItem being injectable if it isn't actually injected.

ENH Avoid "new" keyword to instantiate injectable CMSMenuItem

---

lang/en.yml
templates/SilverStripe/Admin/Includes/LeftAndMain_EditForm.ss
templates/SilverStripe/Admin/Includes/LeftAndMain_PreviewPanel.ss

For some reason, the preview panel template which is referred to in `LeftAndMain::PreviewPanel()` only exists in the cms module for the `CMSMain` controller.
All of the other code for using a CMS preview is available for any arbitrary `LeftAndMain` subclass and is available in this module. There should be no dependency from this module on the cms module to allow previews, and previews should work for all `LeftAndMain` subclasses in this module (e.g. `ModelAdmin`).
Required for #1250
Edit: Depends on silverstripe/silverstripe-framework#10112

ENH: Allow use of the preview panel in any LeftAndMain subclass.

---

code/ModelAdmin.php
code/SecurityAdmin.php

`GridFieldComponent`s packaged with silverstripe/framework will be injectable as of 4.11.0 (see silverstripe/silverstripe-framework#10204)
Explicitly invoking the injector here instead of using `create()` allows backwards compatibility with framework < 4.11.0 while ensuring dependency injection is still used from 4.11.0 onwards.
If core team would prefer, I can instead use the `::create()` static method which was added via the `Injectable` trait - but that will also require updating the constraint for the framework dependency to `^4.11`.

ENH: Prefer dependency injection for GridFieldComponents.

---

code/LeftAndMain.php
tests/php/LeftAndMainTest.php

I've also made the js/css tests a little more robust to make sure the scripts and styles are actually in script/style tags, not just arbitrarily printed in the body.

ENH Allow setting options for extra css/js in LeftAndMain.

---

tests/behat/features/site-settings.feature

Attempt to fix https://app.travis-ci.com/github/silverstripe/silverstripe-installer/jobs/560491370#L1999 which I cannot replicate locally, though I have a feeling there's an cached error page somewhere not being updated when the site title is updated, so instead of serving an unpublished page, serve a published page

MNT Create seperate page for site settings test

---

package.json
yarn.lock

The pattern library is throwing some errors for `isPlainObject.isPlainObject is not a function`. Adding the `is-plain-object` library to admin's dev dependencies fixes it.
- https://github.com/silverstripe/silverstripe-pattern-lib/issues/2

BUG Add missing dependency to build pattern library

---

.travis.yml
composer.json

Fix https://app.travis-ci.com/github/silverstripe/silverstripe-admin/jobs/563165315#L421
Travis failures are related to email, which I think will be fixed separately by https://github.com/silverstripe/silverstripe-behat-extension/pull/210
- fixes https://github.com/silverstripeltd/product-issues/issues/526

MNT Require caret version of frameworktest

---

code/AdminRootController.php
code/CMSBatchAction.php
code/CMSBatchActionHandler.php
code/CMSMenu.php
code/CMSMenuItem.php
code/Forms/UsedOnTable.php
code/GroupImportForm.php
code/LeftAndMain.php
code/MemberImportForm.php
code/ModelAdmin.php
tests/behat/src/AdminContext.php
tests/php/LeftAndMainTest.php
tests/php/ModelAdminTest.php
tests/php/UsedOnTableTest.php

Issue https://github.com/silverstripe/silverstripe-framework/issues/10250

ENH PHP 8.1 compatibility

---

tests/behat/features/gridfield-search.feature

New test cases for GridFIeld. Testing for wrong alert message after getting search result.
- https://github.com/silverstripe/silverstripe-admin/issues/1313

MNT Test cases for testing GridField. Wrong alert issue

---

composer.json

Issue https://github.com/silverstripe/gha-ci/issues/37
Fix failing behat tests https://github.com/silverstripe/silverstripe-admin/runs/7490775317?check_suite_focus=true#step:12:715
silverstripe/frameworktest ^0.4.3 is included in 1.10 composer require-dev and is also in .travis.yml

MNT Require frameworktest

---

_config/forms.yml
code/AdminErrorExtension.php
code/LeftAndMain.php
lang/en.yml
templates/SilverStripe/Admin/Includes/LeftAndMain_Error.ss
tests/behat/features/notfound.feature
tests/behat/src/AdminContext.php

Currently if there is an error in any /admin route, there is no admin-specific way of handling the errors.
This means that if silverstripe/errorpage is installed the user is shown the frontend error page (if there is one) and if it isn't installed or doesn't have a page for the given error, a simple text message is displayed.
This PR renders an error message in the context of the admin, so that users can simply select an appropriate section in the left menu.
The error detail only appears in Dev mode. 
**In this example I tried to navigate to /admin/badonk and an appropriate 404 error is displayed**
**In this example I tried to navigate to /admin/pages/save and an appropriate forbidden error is displayed**
- fixes https://github.com/silverstripe/silverstripe-admin/issues/1232
- fixes …

ENH Display error messages in admin with an admin context

---

code/LeftAndMain.php

Errors happen if php tries to get the value from an uninitailised property, which is causing tests to fail:
https://github.com/silverstripe/silverstripe-cms/runs/7571102762?check_suite_focus=true
> 1) SilverStripe\CMS\Tests\Controllers\CMSMainTest::testCreationOfTopLevelPage
Error: Typed property SilverStripe\Admin\LeftAndMain::$httpErrorMessage must not be accessed before initialization
The new error handling logic should also not apply to AJAX requests, which are likely to format their own errors e.g. in JSON

FIX Don't try to use a property that isn't initialised.

---

code/LeftAndMain.php
tests/behat/features/notfound.feature

The new error handling logic was overwriting JSON error messages, which are most likely responses for AJAX requests. A more complete fix would be to find out why they weren't being detected as AJAX requests and resolve that - but that could lead to even more regressions, and would be time consuming besides.
- https://github.com/silverstripe/silverstripe-admin/issues/1332

FIX Don't overwrite JSON errors with templated error page

---

tests/behat/features/gridfield-search.feature
tests/behat/features/manage-users.feature

Fixes https://github.com/silverstripe/silverstripe-admin/runs/7602647956?check_suite_focus=true
> Form field with id|name|label|value "SearchBox__FirstName" not found. (Behat\Mink\Exception\ElementNotFoundException)
> Form field with id|name|label|value "SearchBox__Name" not found. (Behat\Mink\Exception\ElementNotFoundException)
`SearchBox__` is the prefix for the general search field. `Search__` is the prefix for the advanced filter input fields. These tests have been using the wrong field this whole time.
This has come up because the general search field name is now `q` (so `SearchBox__q`)

MNT Fix behat tests - explicitly use the advanced filter input

---

code/AdminErrorExtension.php

Fixes https://github.com/silverstripe/silverstripe-security-extensions/runs/7602515088?check_suite_focus=true
> SilverStripe\SecurityExtensions\Tests\Control\SudoModeControllerTest::testActivateFailsWithGetRequest
TypeError: SilverStripe\Admin\LeftAndMain::setHttpErrorMessage(): Argument `#1` ($message) must be of type string, null given, called in /home/runner/work/silverstripe-security-extensions/silverstripe-security-extensions/vendor/silverstripe/admin/code/AdminErrorExtension.php on line 21
We shouldn't be trying to pass null where we've declared it should be a string.
We have to accept null into this hook anyway as sometimes that's actually passed in - so it still makes sense for that to be the default here. But we shouldn't pass it through.

FIX Don't pass null as LeftAndMain error message.
