.travis.yml
See https://github.com/silverstripe/silverstripe-framework/issues/6705
=> Drop PHP 5.5 support

.travis.yml, composer.json
See https://github.com/silverstripe/silverstripe-framework/pull/6712
=> Fix builds, build from dev deps

code/CMSMenu.php
Requires https://github.com/silverstripe/silverstripe-framework/pull/6706
=> Update usage of getOwnerModule()

.travis.yml, code/AddToCampaignHandler.php, code/CMSBatchAction.php, code/CMSBatchActionHandler.php, code/CampaignAdmin.php, code/CampaignAdminList.php, code/LeftAndMain.php, composer.json, tests/php/CampaignAdminTest/InvalidChangeSet.php, tests/php/LeftAndMainTest.php
See https://github.com/silverstripe/silverstripe-framework/pull/6725
=> API update for silverstripe/versioned module

.travis.yml, phpunit.xml.dist
See https://github.com/silverstripe/silverstripe-installer/pull/168
=> Update build configuration

client/dist/js/bundle.js, client/dist/styles/bundle.css, client/src/components/FormBuilderModal/FormBuilderModal.js, client/src/components/Modal/Modal.scss, client/src/legacy/AddToCampaignForm.js
https://github.com/silverstripe/silverstripe-framework/issues/6115
=> ENHANCEMENT Support text formatting in modal response

client/dist/js/bundle.js, client/dist/js/vendor.js, client/src/components/Form/Form.js, client/src/components/FormBuilder/FormBuilder.js
This will grant the first field in the Form focus when it is first mounted.
There is a caveat, if there are more than one form, it could lead to race-conditions (whichever form loads last) and possibly undesirables (auto-focus on a field at the bottom of the page).
I had set this to true by default, but looking for feedback if maybe I should set this to false as default.
=> Add an autoFocus property to the Form

code/ModelAdmin.php
=> BUGFIX proper visibility in error message

code/LeftAndMain.php
Dependency of https://github.com/silverstripe/silverstripe-framework/pull/6792
Rebased on top of https://github.com/silverstripe/silverstripe-admin/pull/19 which should be merged first
=> API Major refactor of Hierarchy

client/dist/styles/bundle.css, client/src/components/FieldGroup/FieldGroup.scss, client/src/components/Modal/Modal.scss, client/src/styles/legacy/_forms.scss
Please check https://github.com/silverstripe/silverstripe-framework/issues/6323 for more details
Also fixes Firefox fieldset behaviour
https://github.com/silverstripe/silverstripe-framework/pull/6799
https://github.com/silverstripe/silverstripe-asset-admin/pull/427
=> Fix modal close button style

client/dist/js/bundle.js, client/src/containers/FormBuilderLoader/FormBuilderLoader.js
Related https://github.com/silverstripe/silverstripe-asset-admin/pull/431
=> Fix throw error rather than return empty object

client/dist/styles/bundle.css, client/src/components/ListGroup/ListGroup.scss
Issue: https://github.com/silverstripe/silverstripe-framework/issues/6430
=> Fix asset thumbnail size

themes/cms-forms/templates/SilverStripe/Forms/SelectionGroup.ss
Issue: https://github.com/silverstripe/silverstripe-framework/issues/5706
=> Wrap selection group input in label

client/dist/js/bundle.js, client/src/containers/FormBuilderLoader/FormBuilderLoader.js
Issue: https://github.com/silverstripe/silverstripe-asset-admin/issues/349
=> Show message when viewing file or folder that does not exist

client/dist/js/bundle.js, client/dist/styles/bundle.css, client/src/components/Breadcrumb/Breadcrumb.js, client/src/components/Breadcrumb/Breadcrumb.scss, client/src/components/Breadcrumb/tests/breadcrumb-test.js
Fixes from this before shot
To this after shot
I tested in other admin areas, and have not noticed any regressions
=> Fix breadcrumb chain ellipsis on the left instead of wrap to a new line

client/dist/js/vendor.js, package.json, yarn.lock
More details found here https://github.com/silverstripe/silverstripe-asset-admin/issues/334
This is updating the package.json dependency (and yarn.lock) to include the fix
=> Upgrade react-bootstrap-ss version

client/dist/js/bundle.js, client/src/boot/BootRoutes.js, client/src/boot/tests/BootRoutes-test.js, client/src/legacy/AddToCampaignForm.js, client/src/lib/Config.js, code/LeftAndMain.php
This is so that order priority is enforced when json.stringify is used.
Pull requests which rely on this:
https://github.com/silverstripe/silverstripe-asset-admin/pull/435
https://github.com/silverstripe/silverstripe-campaign-admin/pull/10
https://github.com/silverstripe/silverstripe-frameworktest/pull/33
=> Fix config sections is no longer an associative array

client/dist/js/bundle.js, client/src/components/FormBuilder/FormBuilder.js, client/src/components/TextField/TextField.js
Fixes https://github.com/silverstripe/silverstripe-framework/issues/6741
=> De-couple schema type and type attribute

client/dist/js/bundle.js, client/src/components/Form/Form.js, client/src/components/TextField/TextField.js
BUG Fix issue with empty action holder
required for https://github.com/silverstripe/silverstripe-framework/issues/6063
=> API Make text fields real inputs

client/dist/js/bundle.js, client/src/legacy/LeftAndMain.EditForm.js
The "who can view this" UI is used across multiple admin modules. Moved from CMS to Admin.
=> Move who-can-view toggle from CMS to Admin module

client/dist/js/bundle.js, client/dist/js/vendor.js, client/src/components/TextField/TextField.js
Issue: https://github.com/silverstripe/silverstripe-asset-admin/issues/177
=> Add autofocus flag

client/dist/js/bundle.js, client/src/components/FormAction/FormAction.js, client/src/legacy/LeftAndMain.js, client/src/lib/castStringToElement.js, themes/cms-forms/templates/SilverStripe/Forms/FormAction.ss
To be closer to React's implementation
Fixes https://github.com/silverstripe/silverstripe-framework/issues/6439
Dependencies:
https://github.com/silverstripe/silverstripe-framework/pull/6907
https://github.com/silverstripe/silverstripe-cms/pull/1819
=> Fix update ss template FormActions

client/dist/js/bundle.js, client/src/legacy/GridField.js
Replaces https://github.com/silverstripe/silverstripe-framework/pull/6586
=> BUG Use correct timeout for modal fade out

client/dist/js/bundle.js, client/src/components/TreeDropdownField/TreeDropdownField.js
Found during a visual test of https://github.com/silverstripe/silverstripe-asset-admin/issues/217
=> Fix readonly mode for TreeDropdownField

client/dist/js/TinyMCE_sslink-external.js, client/src/legacy/TinyMCE_sslink-external.js
Feedback from https://github.com/silverstripe/silverstripe-admin/pull/58#pullrequestreview-38345710
=> Fix open up external link to protocols outside http(s)

client/dist/js/bundle.js, client/src/i18n.js
Fixes https://github.com/silverstripe/silverstripe-framework/issues/1619
=> BUG Ensure i18n detects locale from <html lang>

code/CMSBatchAction.php, code/CMSMenu.php, code/CMSMenuItem.php, code/LeftAndMain.php
See https://github.com/silverstripe/silverstripe-framework/issues/6085
=> Remove object class

client/dist/js/TinyMCE_sslink-email.js, client/dist/js/TinyMCE_sslink-external.js, client/dist/js/bundle.js, client/dist/js/vendor.js, client/src/legacy/AddToCampaignForm.js, client/src/legacy/TinyMCE_sslink-email.js, client/src/legacy/TinyMCE_sslink-external.js
Requried for https://github.com/silverstripe/silverstripe-asset-admin/pull/487 to pass
=> Fix for entwine using react code, now they need injector wrapped

code/AdminRootController.php, code/LeftAndMain.php, tests/php/CMSProfileControllerTest.php, tests/php/LeftAndMainTest.php, tests/php/SecurityAdminTest.php
Main issue: https://github.com/silverstripe/silverstripe-framework/issues/6681
See https://github.com/silverstripe/silverstripe-framework/pull/7037 for framework pull request
=> [WIP] App object refactor

_config.php, code/LeftAndMain.php, code/MemberImportForm.php, code/SecurityAdmin.php, templates/SilverStripe/Admin/Includes/CMSLoadingScreen.ss, templates/SilverStripe/Admin/LeftAndMain.ss
Relies on https://github.com/silverstripe/silverstripe-framework/pull/7065
=> [WIP] Remove reliance on MODULE_DIR constants.

.upgrade.yml, code/LeftAndMain.php
Part of https://github.com/silverstripe/silverstripe-framework/issues/7104
=> BUG Implement or exclude all pending upgrader deltas

templates/SilverStripe/Admin/Includes/LeftAndMain_MenuList.ss
Issue: https://github.com/silverstripe/silverstripe-admin/issues/135
=> FIX broken menu items for model admins

_config.php
=> check for already set config in tinymce

_config/modules.yml, _config/tinymce.yml
Required for https://github.com/silverstripe/silverstripe-framework/pull/7154
Main issue: https://github.com/silverstripe/silverstripe-framework/issues/7115
=> API Update module sorting

code/LeftAndMain.php
Requires https://github.com/silverstripe/silverstripe-framework/pull/7151
=> NEW Use injector for creating SSViewer

code/LeftAndMain.php
Following from https://github.com/silverstripe/silverstripe-framework/pull/7125 which was merged up to `4` in the framework, this pull request uses the version provider dependency from the framework to get `::CMSVersion`
=> NEW Add version provider dependency to use for CMSVersion

code/CMSBatchActionHandler.php, tests/php/SecurityAdminTest.php
In preparation for https://github.com/silverstripe/silverstripe-framework/issues/6803
=> FIX Use merge instead of update for config calls

code/LeftAndMain.php
Related PR that made this change: #153
=> FIX Add getter and setter for the version provider dependency on LeftAndMain

code/LeftAndMain.php, code/ModelAdmin.php, tests/php/CMSMenuTest.php
See https://github.com/silverstripe/silverstripe-framework/pull/7298
=> Replace use of Configurable stat() with config()->get(), will be deprecated in future

code/LeftAndMain.php
Resolves https://github.com/silverstripe/silverstripe-cms/issues/1938
=> Add generic permission check for direct access to LeftAndMain

code/LeftAndMain.php
To allow extensions to update the config
Related PR: https://github.com/silverstripe/silverstripe-cms/pull/1959
=> NEW Allow LeftAndMain::getClientConfig to be extensible

code/CMSBatchActionHandler.php, code/LeftAndMain.php
This is instead of updating config... every request.
Please check https://github.com/silverstripe/silverstripe-admin/issues/264 for more details
Depends on https://github.com/silverstripe/silverstripe-framework/pull/7392
=> Enahncement use the new setter and getter for LeftAndMain init

_config.php, phpunit.xml.dist, templates/SilverStripe/Admin/Includes/CMSLoadingScreen.ss
Parent story https://github.com/silverstripe/silverstripe-framework/issues/7405
=> Fix regressions in vendor migration

package.json, yarn.lock
https://github.com/silverstripe/silverstripe-framework/issues/7405
=> Upgrade webpack config to 0.4.0

thirdparty/tinymce/tiny_mce_gzip.php
Please see https://github.com/silverstripe/silverstripe-framework/issues/4548 for more details
Requires https://github.com/silverstripe/silverstripe-framework/pull/7451
=> rename TEMP_FOLDER to TEMP_PATH

code/Forms/GridFieldPrintButtonExtension.php, code/LeftAndMain.php
Parent issue https://github.com/silverstripe/silverstripe-admin/issues/299
=> Fix icon urls and deprecated resource api usages

code/LeftAndMain.php
Fixes https://github.com/silverstripe/silverstripe-framework/issues/7111
=> Fix remove unnecessary escape

code/LeftAndMain.php
=> DOCS Minor docblock fix

code/LeftAndMain.php
Related: https://github.com/silverstripe/silverstripe-framework/issues/7631
=> Minor cleanup of linting issues / phpdocs

.travis.yml
Will simplify merge up and future tests.
=> ENHANCEMENT Use recipes for test configuration

.gitattributes, .gitignore
Also included some source asset files which are not needed
Parent issue: https://github.com/silverstripe/silverstripe-framework/issues/6890
=> Set .gitattributes to ignore docs and tests folder

code/SecurityAdmin.php
Replaces https://github.com/silverstripe/silverstripe-framework/pull/7646
Fixes #256
=> ENHANCEMENT Put gridfield page count in button toolbar for security admin

templates/SilverStripe/Admin/Includes/LeftAndMain_MenuLogo.ss
=> BUG Fix $CMSVersion appearing visually

code/LeftAndMain.php
Requires https://github.com/silverstripe/silverstripe-versioned/pull/45
Parent story https://github.com/silverstripe/silverstripe-cms/issues/1578
=> ENHANCEMENT Set default reading mode in admin (disables stage=Stage rewrite links)

lang/en.yml, templates/SilverStripe/Admin/Includes/ModelAdmin_Content.ss, templates/SilverStripe/Admin/Includes/ModelAdmin_Tools.ss
=> Rename "Filter" label to "Search"

.upgrade.yml
Remove duplicate keys
Parent issue https://github.com/silverstripe/silverstripe-upgrader/issues/72
Validated using https://yamlvalidator.com/
=> BUG Fix invalid .upgrade.yml

code/LeftAndMain.php
=> FIX Update user help link to 4

lang/en.yml, templates/SilverStripe/Admin/Includes/LeftAndMain_MenuStatus.ss
=> Add missing title attribute to profile link

_config/routes.yml
Related to https://github.com/silverstripe/silverstripe-graphql/issues/158
=> BUGFIX: graphql route getting overwritten

templates/SilverStripe/Admin/Includes/LeftAndMain_MenuToggle.ss
See [#615]( https://github.com/silverstripe/silverstripe-admin/pull/615#issuecomment-427324114)
=> FIX Add fix for potential tabnabbing on community help links

code/ModelAdmin.php
Fix silverstripe/silverstripe-framework#8454
=> BUG ModelAdmin pagination with a filter

.gitignore, .travis.yml
This is a hackday project. This updates our travis config to auto-publish the pattern-lib to gh-pages whenever a new commit is added to the `1` branch.
=> MINOR Auto-publish pattern-lib to gh-pages

code/CMSBatchAction.php, code/LeftAndMain.php
Issue: https://github.com/silverstripe/silverstripe-framework/issues/8424
=> FIX Replace usage of Convert JSON methods with json_encode and json_decode

code/Forms/EditorEmailLinkFormFactory.php, code/Forms/LinkFormFactory.php
Issue: https://github.com/silverstripe/silverstripe-cms/issues/2273
=> NEW Add update extension hooks for LinkFormFactory subclasses

tests/behat/features/reauthenticate.feature
Fixes #778 race between search component and login iframe
=> Fix reauthenticate behat tests

README.md
helpfulrobot.io now leads to a very broken clothing website
=> Remove Helpful Robot badge from README

code/ModelAdmin.php
Also remove unused class imports
=> Use correct deprecation notice "from" versions

package.json, yarn.lock
Fix some outstanding issue from https://github.com/silverstripe/silverstripe-admin/pull/845
=> BUG Increment bootstrap requirements

code/ModelAdmin.php
=> BUG Fix ModelAdmin ignoring page_length

package.json, yarn.lock
- This update fixes one of issues using `ListboxField` which would show the wrong suggestion(s) upon typing special characters like dollar sign, single quote, etc
=> Update chosen-js version in package.json

composer.json, tests/php/LeftAndMainTest.php
Upgrade to phpunit 8
related:
- https://github.com/silverstripe/silverstripe-cms/pull/2532
=> Upgrade to phpunit 8

.storybook/preview-head.html, client/src/font/tests/Icons-story.js
This makes it really clear for people where icons should be used. 
Have also added an option to add a summary to allow for further description of each section in the future:
=> ENHANCEMENT: Split icon storybook into sections

code/LeftAndMain.php
Follow up for: #1013 
Need to add BC support for the old `getCMSValidator()` method in case someone is on an older version of `framework`.
=> Follow up: Add BC support for getCMSValidator

code/LeftAndMain.php
Added functionality to retain current page id while in ModelAdmin
=> currentPageID() does not work in ModelAdmin

client/src/components/Tip/README.md
=> DOC Change addTip() reference to TextField.php

code/ModelAdmin.php
Issue: https://github.com/silverstripe/silverstripe-framework/issues/1915
=> ENH Replace E_USER_ERROR errors with exceptions

.travis.yml, client/lang/src/en.json
Reverts just this file in this commit
https://github.com/silverstripe/silverstripe-admin/commit/74e754612902974f157674b7dd28b4419612d45c#diff-1448c16303b78bb50864a0a00032d3e27e28f97c7f1e0e615aa95562c0d22efcL26
Do this post merge:
`tx push -s`
=> Revert translation updates

.sass-lint.yml, .travis.yml, composer.json, phpcs.xml.dist
sass-lint changes are so that sass-lint doesn't run on vendor/silverstirpe/asset-admin =)
=> MNT Travis shared config, use sminnee/phpunit

tests/behat/features/multitab-validation.feature, tests/behat/src/AdminContext.php
Issue https://github.com/silverstripe/silverstripe-behat-extension/issues/200
=> MNT Use behat-extension function for clicking elements

.travis.yml
Issue https://github.com/silverstripe/silverstripe-admin/issues/1212
=> MNT Disable pattern-lib

tests/php/CMSProfileControllerTest.php, tests/php/LeftAndMainTest.php, tests/php/SecurityAdminTest.php
Issue https://github.com/silverstripe/recipe-cms/issues/47
=> MNT Update tests to use logInAs()

tests/behat/features/manage-users.feature, tests/behat/features/multitab-validation.feature, tests/behat/features/profile.feature, tests/behat/features/site-settings.feature
Issue https://github.com/silverstripeltd/product-issues/issues/473
=> MNT Update behat tests

.github/workflows/update-js-deps.yml, .github/workflows/update-js.yml
Issue https://github.com/silverstripe/gha-update-js/issues/5
=> MNT Use up­date-js action
